### ISSUE TITLE
Remove redundant default metrics

### ISSUE THREAD

**Issue by Nightfall-Rain** [fstab/grok_exporter#108]
I am using grok exporter to dealing with my application log files. I don't care about the default metrics, such as go_gc info，go_memstats info and so on. Is there anyway or configs to forbid collect this metrics. Thank you!

**Comment by fstab** [comment]
Yes, there is a new command line flag `-disable-exporter-metrics`. However, this was implemented after releasing 1.0.0.RC3, so you have to build `grok_exporter` from the current `master` branch, or wait for the next release.

**Comment by Nightfall-Rain** [comment]
that's great!
