### ISSUE TITLE
Feature Request: Availability for x86_64 Linux Architecture

### ISSUE THREAD

**Issue by surajrmysuru** [fstab/grok_exporter#109]
Dear Team,

I would like to know if there is any plans of releasing this to run Redhat having x86_64 architecutre.

Kindly let me know.

Thanks and Regards,
Suraj

**Comment by fstab** [comment]
The linux-amd64 releases should run on x86_64. Please try this and report back if there are any issues with that.

**Comment by surajrmysuru** [comment]
Hi Fabian. 

Thanks for your reply. I tried but I am getting permission denied error while trying to run the exporter.
'bash: ./grok_exporter: Permission denied'

I tried both grok_exporter-1.0.0.RC3.linux-amd64 and grok_exporter-1.0.0.RC3.linux-arm64v8.

Thanks,
Suraj

**Comment by fstab** [comment]
Can you run the two commands `id` and `ls -l grok_exporter` in the `grok_exporter-1.0.0.RC3.linux-amd64` directory and tell me the output?

**Comment by surajrmysuru** [comment]
Here you go

> Id

uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023

> ls -l

drwxr-xr-x. 2 root root      106 Feb 14 22:13 example
-rwxr-xr-x. 1 root root 24492168 Feb 14 22:13 grok_exporter
drwxr-xr-x. 2 root root     4096 Jan 12  2019 patterns
