### ISSUE TITLE
Counter metric type does not support value

### ISSUE THREAD

**Issue by pelov** [fstab/grok_exporter#110]
In the documentation of the [counter metric type](https://github.com/fstab/grok_exporter/blob/master/CONFIG.md#counter-metric-type) it is stated that it supports `value` configuration which should evaluate to a positive number. And this makes a lot of sense for counters that accumulate things like durations, sizes, etc. However, running the grok_exporter gives an error:

> Failed to load web.yml: Invalid metric configuration: 'metrics.value' cannot be used for counter metrics.

**Comment by fstab** [comment]
I am too slow releasing. The documentation is already updated, but the `value` for counter metrics is not included in 1.0.0.RC3. Sorry for that, I'll create a release ASAP. Alternatively, build `grok_exporter` from the current sources, then it'll work.

**Comment by pelov** [comment]
Yes, it works on branch master. Thanks!
