### ISSUE TITLE
Rsyslog & Redis tailer integrations

### ISSUE THREAD

**Issue by hartfordfive** [fstab/grok_exporter#130]
@fstab, I realize my Kafka tailer PR is still pending, although I'm also considering adding a syslog and Redis integration.  Any objections to that?

**Comment by fstab** [comment]
I'm happy to hear that you want to continue working on new tailers. I just commented on the Kafka PR.

**Comment by hartfordfive** [comment]
@fstab , any news on when you'll be creating the latest release with the Kafka integration?  I actually need to start using the Kafka integration although I figured I'd check with you first before I compile my own build in case you have some other fixes you plan on adding in?   Thanks again!

**Comment by fstab** [comment]
I'll try to get it done until Sunday.

**Comment by fstab** [comment]
Quick update: I need to postpone the release until tomorrow.

**Comment by hartfordfive** [comment]
No worries and thanks for the update.

**Comment by fstab** [comment]
1.0.0.RC5 is out. Thanks for your contribution. BTW I added the `vendor/` folder again, because you are right, this is an easy way to make the build reproducible even if someone removes a dependency from GitHub.
