### ISSUE TITLE
Requesting updated tailer documentation

### ISSUE THREAD

**Issue by jdrews** [fstab/grok_exporter#131]
I watched your presentation at [FOSDEM 2017: Implementing 'tail -f' in Go](https://www.youtube.com/watch?v=lLDWF59aZAo). Very good talk! I'd like to follow your path to get tailing working on a Go rewrite of my simple [logstation](https://github.com/jdrews/logstation). 

Can you provide some updated documentation for your wiki? Looks like those files (fileTailer_linux.go, etc) have been replaced in recent years and I'd like to know how to use the new code.
https://github.com/fstab/grok_exporter/wiki/tailer-(tail-%E2%80%90f)

Thanks!

**Comment by jdrews** [comment]
I think I can help update the documentation via PR to include how to use your tailer as a library. Before that, I could use some guidance, please. 

I've been digging into how grok_exporter uses tailer. My goal was to import your tailer codebase and use it to `tail -f` for new lines and pipe them into my function with a Go channel. 

The problem I'm seeing is that the FileTailer.Lines() channel always has *all* lines in the file, instead of only the new lines. Maybe this is Windows bug? 

Here's my code

``` go
func follow(path string, conn *websocket.Conn) error {
	logger := logrus.New()
	logger.Level = logrus.DebugLevel
	logger.SetOutput(os.Stdout)

	parsedGlob, err := glob.Parse(path)
	if err != nil {
		logger.Error("%q: failed to parse glob: %q", parsedGlob, err)
		return err
	}

	tailer, err := fswatcher.RunFileTailer([]glob.Glob{parsedGlob}, false, true, logger)
	for {
		select {
		case line := <- tailer.Lines():
			logger.Debug(line.Line)
			conn.WriteMessage(websocket.TextMessage, []byte(line.Line))
		}
	}
}
```
If I write a line that say "line 1" to a logfile. I get this in the stdout:
```
time="2020-09-13T01:34:45-04:00" level=debug msg="received event: \"E:\\\\git\\\\logstation\\\\test/logfile.log\": 0x2 == FS_MODIFY" directory="E:\\git\\logstation\\test"
time="2020-09-13T01:34:45-04:00" level=debug msg="read line \"line 1\""
time="2020-09-13T01:34:45-04:00" level=debug msg="line 1"
time="2020-09-13T01:34:45-04:00" level=debug msg="received event: \"E:\\\\git\\\\logstation\\\\test/logfile.log\": 0x2 == FS_MODIFY" directory="E:\\git\\logstation\\test"
```
If if append "line 2" to the logfile I end up with this in the stdout:
```
time="2020-09-13T01:34:48-04:00" level=debug msg="received event: \"E:\\\\git\\\\logstation\\\\test/logfile.log\": 0x2 == FS_MODIFY" directory="E:\\git\\logstation\\test"
time="2020-09-13T01:34:48-04:00" level=debug msg="received event: \"E:\\\\git\\\\logstation\\\\test/logfile.log\": 0x2 == FS_MODIFY" directory="E:\\git\\logstation\\test"
time="2020-09-13T01:34:48-04:00" level=debug msg="read line \"line 1\""
time="2020-09-13T01:34:48-04:00" level=debug msg="read line \"line 2\""
time="2020-09-13T01:34:48-04:00" level=debug msg="line 1"
time="2020-09-13T01:34:48-04:00" level=debug msg="line 2"
```

Notice how it has both "line 1" and "line 2" in the channel. I was hoping when I appended "line 2" to the log file, I would only get "line 2" in the `tailer.Lines()` Go channel. 

Finally, I should wrap this up by saying that I'm in the midst of learning Go... so apologies if I'm doing something elementary. Thanks for the help!

**Comment by fstab** [comment]
It depends on how you write _line 2_ to the file.

If you open the file in a text editor, add a line, and save it, the text editor will actually re-write the entire file. `grok_exporter` will see that the entire file has been overwritten, and start reading from the beginning.

A good way for testing is opening a `cmd` window and typing the command

```
echo "line 2" >> logfile.log
```

This should append "line 2" to the file without re-writing the whole file. This should work with `grok_exporter`.

**Comment by jdrews** [comment]
That worked perfectly! 

Going to close this ticket. I'll make a PR with some updated documentation on using tailer as a library/package. Thanks for the help!
