### ISSUE TITLE
prometheus doesnot display correct count (number of lines)

### ISSUE THREAD

**Issue by spbangalore** [fstab/grok_exporter#132]
I have configured prometheus  and Grok exporter on same RHEL 7.6 (Maipo) machine.
1. After re-start first time its read log file abc.out and show the count (lets say we have entry like 
HELLO
HI 
HI) , show in prometheus I can see the count HELLO - 1 and HI - 2.
2. Now lets say we have updated abc.out as HELLO and HI only (So, in prometheus it should show as  HELLO - 1 and HI - 1). However the actual new count is showing as HELLO - 2 and HI - 3).
3. What its looks like is the count is getting added on every update of abc.out file, instead showing or reading the correct actual values/number of lines.

Version :- 
prometheus-2.20.1
grok_exporter-1.0.0

Below are some configuration part :-
prometheus.yml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  - job_name: 'Grok exporter'
    scrape_interval: '30s'
    metrics_path: '/metrics'
    static_configs:
     - targets: ['localhost:9144']

grok_exporter config.yml :-
global:
  config_version: 3
  poll_interval_seconds: 5

**Comment by spbangalore** [comment]
I think its because of 'type: counter'. any example for 'type: gauge' with respect to above case?

**Comment by spbangalore** [comment]
**Anyone tried this for logs path, with grok config_version: 3?**

**Comment by fstab** [comment]
Hi @spbangalore, how did you update the log file? Did you edit it in a text editor? Usually text editors don't append lines to files. They remove the file and replace it with a new file. What `grok_exporter` sees is a new file was created and `HELLO` was written to the new file, so `grok_exporter` adds 1 to the number of `HELLO` lines.

In order to simulate the behavior of a real logging application, open a `cmd` window and type a command like

```
echo "HI" >> logfile.log
```

This will actually _append_ a line to the file like a log application does, and `grok_exporter` should count this correctly.

**Comment by spbangalore** [comment]
> Hi @spbangalore, how did you update the log file? Did you edit it in a text editor? Usually text editors don't append lines to files. They remove the file and replace it with a new file. What `grok_exporter` sees is a new file was created and `HELLO` was written to the new file, so `grok_exporter` adds 1 to the number of `HELLO` lines.
> 
> In order to simulate the behavior of a real logging application, open a `cmd` window and type a command like
> 
> ```
> echo "HI" >> logfile.log
> ```
> 
> This will actually _append_ a line to the file like a log application does, and `grok_exporter` should count this correctly.

Dear Fabian,

I have tried this (echo "HI" >> logfile.log) to append. but its keep increasing, when 'readall: false' .
If 'readall: true', and I use (echo "HI" |> logfile.log) , its showing the value incremented, however we have one entry only.

So, I want to know use  'readall: true' then instead of counter how can I use gauge, so that I can get the exact number of entry/lines found from the begging.

**Comment by fstab** [comment]
The `grok_exporter` config above is not complete, could you post the complete config? I'll have a look. Moreover, please remove `poll_interval_seconds: 5`, because that will switch to a mode where `grok_exporter` polls the file system every 5 seconds, and this should not be needed in your case.

**Comment by spbangalore** [comment]
Dear Fabian,

Please see below the config.yml for "
https://github.com/fstab/grok_exporter/issues/132"

-bash-4.2$ cat config.yml
global:
  config_version: 3
input:
  poll_interval: 5s
  type: file
  path: /opt/grok_exporter-1.0.0.RC5.linux-amd64/abc.out
  readall: false # Read from the beginning of the file? False means we
start at the end of the file and read only new lines.
imports:
- type: grok_patterns
  dir: ./patterns
grok_patterns:
- 'EXIM_MESSAGE [a-zA-Z ]*'
metrics:
- type: counter
  name: cm_process_count
  help: Total cm_process count.
  match: '/opt/portal/7.5/bin/cm'
- type: counter
  name: dm_oracle_process_count
  help: Total dm_oracle_process count.
  #match: '%{EXIM_DATE} %{EXIM_REMOTE_HOST} F=<%{EMAILADDRESS}> rejected
RCPT <%{EMAILADDRESS}>: %{EXIM_MESSAGE:message}'
  match: '/opt/portal/7.5/bin/dm_oracle'
- type: counter
  name: dm_ifw_sync_process_count
  help: Total dm_ifw_sync_process count.
  match: '/opt/portal/7.5/bin/dm_ifw_sync'
labels:
    error_message: '{{.message}}'
    logfile: '{{base .logfile}}'
server:
  protocol: http
  port: 9144

**Comment by spbangalore** [comment]
> The `grok_exporter` config above is not complete, could you post the complete config? I'll have a look. Moreover, please remove `poll_interval_seconds: 5`, because that will switch to a mode where `grok_exporter` polls the file system every 5 seconds, and this should not be needed in your case.

Thanks for the update Fabian, sent you the configuration details.

**Comment by fstab** [comment]
Something's got to be wrong with the config file you sent me.

1) There are matches for `/opt/portal/7.5/bin/cm`, `/opt/portal/7.5/bin/dm_oracle`, and `/opt/portal/7.5/bin/dm_ifw_sync` but not for `HELLO` and `HI` as you used in your test.
2) The 3rd match `/opt/portal/7.5/bin/dm_ifw_sync` uses a label `{{.message}}`, but there is no grok field `message` in the match. `grok_exporter` does not start with this config. It terminates immediately with an error saying `dm_ifw_sync_process_count: grok field message not found in match pattern`.

It seems like you accidentally sent the wrong config file. Please double-check if this is the configuration you used for your test.

**Comment by spbangalore** [comment]
> Something's got to be wrong with the config file you sent me.
> 
> 1. There are matches for `/opt/portal/7.5/bin/cm`, `/opt/portal/7.5/bin/dm_oracle`, and `/opt/portal/7.5/bin/dm_ifw_sync` but not for `HELLO` and `HI` as you used in your test.
> 2. The 3rd match `/opt/portal/7.5/bin/dm_ifw_sync` uses a label `{{.message}}`, but there is no grok field `message` in the match. `grok_exporter` does not start with this config. It terminates immediately with an error saying `dm_ifw_sync_process_count: grok field message not found in match pattern`.
> 
> It seems like you accidentally sent the wrong config file. Please double-check if this is the configuration you used for your test.

1. 	Sorry for the confusion,  in the initial I thought someone have worked on this, so gave a simple example. 
2. 	I have removed now below 3 lines from config.yml, and don’t see any error in nohup.out.
labels:
    error_message: '{{.message}}'
    logfile: '{{base .logfile}}'

Let me explain again :-
I started grok_exporter and run below (with few min interval), with same config.yml (without label {{.message}} as you mentioned in point number-2):-
ps -ef|grep 'cm$\|dm_oracle\|dm_ifw_sync' |grep bin >> abc.out
Refer screenshots from Grafana :-
![cm dm process](https://user-images.githubusercontent.com/45715256/94516381-5231ec80-0243-11eb-861b-91fbf7a133e9.JPG)


However, since all process are running fine (So count will be same) and same number of process will be pushed in abc.out file.
**However, my requirement is to display the count what is inserted only (not keep adding to existing values).**

**Comment by fstab** [comment]
Ok, I think I understand what you want. There are two options.

1) If you update the file at a regular time interval, you can use the Prometheus [increase()](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) function to query how much the count was increased. For example, to learn how much the `dm_oracle_process_count` increased in the last 5 minutes use
    ```
    increase(dm_oracle_process_count[5m])
    ```

2) You write the actual number of processes into your logfile, for example like this:
    ```
    echo "the number of dm_oracle processes is $(ps -ef | grep dm_oracle | grep bin | wc -l)" >> abc.out
    ```
    Then you can use a `gauge` metric to get the latest value:
    ```yaml
    - type: gauge
      name: dm_oracle_process_count
      help: Current number of dm_oracle processes
      match: 'the number of dm_oracle processes is %{INT:number}'
      value: '{{.number}}'
    ```

**Comment by spbangalore** [comment]
> Ok, I think I understand what you want. There are two options.
> 
> 1. If you update the file at a regular time interval, you can use the Prometheus [increase()](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) function to query how much the count was increased. For example, to learn how much the `dm_oracle_process_count` increased in the last 5 minutes use
>    ```
>    increase(dm_oracle_process_count[5m])
>    ```
> 2. You write the actual number of processes into your logfile, for example like this:
>    ```
>    echo "the number of dm_oracle processes is $(ps -ef | grep dm_oracle | grep bin | wc -l)" >> abc.out
>    ```
>    
>    
>    Then you can use a `gauge` metric to get the latest value:
>    ```yaml
>    - type: gauge
>      name: dm_oracle_process_count
>      help: Current number of dm_oracle processes
>      match: 'the number of dm_oracle processes is %{INT:number}'
>      value: '{{.number}}'
>    ```

Thank you Fabian,
With option-2 I am able to get now correct data. However need below information further on same :-
1. How can we implement this for float values (example memory usage is 17.94)?
2. How can we implement this for any string value?
3. I think there won't be any issue if we insert multiple entry (may be from multiple cron jobs, or scripts) will there be any issue. Have seen this before or any limit?

**Comment by fstab** [comment]
1. Easy. Just change the `match` to
    ```yaml
    match: 'the number of dm_oracle processes is %{NUMBER:number}'
    ```
2. You cannot use strings as values in a time series, but you can use strings as labels. Example:
    ```yaml
    - type: gauge
      name: test_numbers
      help: Current number of dm_oracle processes
      match: 'the number of %{WORD:name} processes is %{NUMBER:number}'
      value: '{{.number}}'
      labels:
        name: '{{.name}}'
    ```
    If the above matches a line like
    ```
    the number of dm_oracle processes is 7.43
    ```
    you get a Prometheus metric like
    ```
    test_numbers{name="dm_oracle"} 7.43
    ```
3. Should not be an issue. I would not expect any limit in your scenario.

**Comment by spbangalore** [comment]
Dear Fabian,
I can see all others result for Prometheus console/graph.

However its not working for below configuration -

config.yml (few entries, others output is )
input:
  poll_interval: 10s
  type: file
  path: /scratch/installables/prometheus/grok_exporter/grok_exporter-1.0.0.RC5.linux-amd64/abc.out

- type: gauge
  name: Testnap_status
  help: The Testnap_connectivity_status is
  match: 'The Testnap_connectivity_status is %{INT:number}'
  value: '{{.number}}'

abc.out entry (This come after appending 'using >> operator' as we discussed on previous conversations :-
Testnap_status 1

prometheus console/graph output (It should be 1) :-
Testnap_status{instance="*******.**.****.***:9144",job="Grok exporter"}	0

**Comment by spbangalore** [comment]
Its resolved..
