### ISSUE TITLE
Problem with value for big numbers

### ISSUE THREAD

**Issue by slima** [fstab/grok_exporter#137]
I have input:

source: 10.214.32.43 data for group: 239.240.1.69 data: 1708291885608 0 164684 0
source: 10.214.32.43 data for group: 239.240.1.69 data: 1708311884860 0 164684 0
source: 10.214.32.43 data for group: 239.240.1.69 data: 1708331882796 0 164684 0

and config:

```
metrics:
- type: gauge
  name  : dvblast_packets
  help  : dvblast_packets reaport
  match : 'source:\s%{IPV4:sonda}\sdata\sfor\sgroup:\s%{IPV4:group}\sdata:\s%{GREEDYDATA:packets}\s%{GREEDYDATA:seq_errors}\s%{GREEDYDATA:errors}\s%{GREEDYDATA:scrambled}'
  value : '{{.packets}}'
  labels:
    sonda     : '{{.sonda}}'
    group     : '{{.group}}'
  retention: 1m
```

and for packets = 1708531867420
I got: dvblast_packets{group="239.240.1.97",sonda="10.214.32.43"} 2.135537935356e+12

so it is not true.

Any idea why?

**Comment by fstab** [comment]
I tried it and it shows the correct result
```
dvblast_packets{group="239.240.1.69",sonda="10.214.32.43"} 1.708331882796e+12
```
Any hint how I could reproduce this? Maybe, as the IP address in `group` differs, you were looking at another example?

**Comment by slima** [comment]
Oh, shame on me! You are right. I checked another group for the same sonda. Result is right. Sorry for creating this false issue.
