### ISSUE TITLE
inotify not working in docker

### ISSUE THREAD

**Issue by kevinkk525** [fstab/grok_exporter#143]
I built grok_exporter docker-container with the dockerfile from #62 and in the config file "readall=false" and no poll interval but grok_exporter doesn't pick up any line changes.
host system is ubuntu 20.04.

Running the binary on the host system works fine with inotify, just the docker doesn't. Maybe someone can help me with that issue?

**Comment by kevinkk525** [comment]
ok this one I solved, inotify doesn't work if you bind the source logfile into the container. If you just bind/mount the directory of the logfile then it works. Sorry.

**Comment by fstab** [comment]
Thanks for commenting the solution after you found it. This will certainly be appreciated by others having the same issue.
