### ISSUE TITLE
verbose logging in grok_exporter?

### ISSUE THREAD

**Issue by jesperronn** [fstab/grok_exporter#145]
First, thanks for creating and maintaining this tool.

Forgive my lack of knowledge, but I am looking if there is an easy way to give a --verbose flag to the tool, (or --debug, or --trace) which can help me debug my configuration when I am working on the matchers.

thanks in advance!

**Comment by fstab** [comment]
Unfortunately there is no good verbose option right now.

If you want to debug grok pattern, there are multiple grok pattern test websites on the Internet where you can test a pattern and example log lines.

For debugging within `grok_exporter` itself, the best way to debug is to look the `grok_exporter_lines_matching_total` [built-in metric](https://github.com/fstab/grok_exporter/blob/master/BUILTIN.md). I am currently working on improving this (branch _built-in-metrics-improvement_), but that's work in progress.

**Comment by jesperronn** [comment]
Thanks for the update @fstab. Looking forward to improved debug/logging abilities later :)
