### ISSUE TITLE
RFC: Replacing oniguruma with a go regex module

### ISSUE THREAD

**Issue by sighingnow** [fstab/grok_exporter#162]
Hi @fstab,

Thanks for the wonderful work! I'm wondering if there's any particular consideration of using libonig as the regex engine? It would be great if it could be replaced by a go regex pattern for easier deployment, e.g., if there's no extra dependency we could just put the binary generated by go into a alpine linux based container.

**Comment by sighingnow** [comment]
If there's no such consideration and such change is acceptable, I could prepare a PR then.

**Comment by fstab** [comment]
The problem is that the built-in Go regular expressions don't support backtracking, but many grok patterns use backtracking. https://github.com/fstab/grok_exporter/wiki/About-the-Regular-Expression-Library

**Comment by sighingnow** [comment]
Thanks for pointing me to the link.

Closing.
