### ISSUE TITLE
Exclude char

### ISSUE THREAD

**Issue by dex2103** [fstab/grok_exporter#178]
Hi,
I try to use grok exporter for reading logs (/var/log/audit/audit.log) to prometheus. I Iooking for solution for exclude one character "(" from exporting data. This file have log data with process number like this: (1658738290.750:4994). So I get from grok (1658738290.750 with this pattern: I use pattern:  msg=audit(%{MESSAGE:msg}:%{MESSAGE:id}), but I would like remove char "(". 
It is possible with grok exporter ?

**Comment by byzent** [comment]
Something like this in your grok config yaml file:

grok_patterns:
    - 'MESSAGE %{POSINT}.*?%{POSINT}'
match: ".*?%{MESSAGE:msg}.*?%{POSINT:id}.*?"

Note that .*? will skip 1 character

**Comment by dex2103** [comment]
Thank you in this case I used msg=audit[(]%{MESSAGE:msg}:%{MESSAGE:id}[]) but .*? is good resolve. 
Thanks, I close issue.
