### ISSUE TITLE
grok exporter should be able to start if file does not exist

### ISSUE THREAD

**Issue by roidelapluie** [fstab/grok_exporter#23]

**Comment by roidelapluie** [comment]
If a file does not exist, the grok export should start. Thet it would wait with inotify for file to be present.

I propose a new metric as well: grok_pen_files_count (gauge)

**Comment by fstab** [comment]
This is definitely useful. I think it should be configurable. Maybe it is still good to keep the current behaviour as default, because if the log file is missing it is very likely a configuration error.

**Comment by fstab** [comment]
I implemented a new config option for the `input` section:

```yaml
fail_on_missing_logfile: false
```

It's not released and documented yet, but it's pushed to the master branch. The `grok_pending_files_count` metric is still missing.
