### ISSUE TITLE
Summary percentile sliding window

### ISSUE THREAD

**Issue by roidelapluie** [fstab/grok_exporter#24]
Hi

When using summary, what is the sliding window used for the percentiles?

**Comment by fstab** [comment]
It's the default from [client_golang](https://github.com/prometheus/client_golang), which is 10 minutes (with 5 Buckets, i.e. every 2 minutes the window is moved forward). Do you think this should be configurable?

**Comment by roidelapluie** [comment]
No because summaries are useless when you have more than 1 server..

**Comment by fstab** [comment]
Added this to [CONFIG.md](https://github.com/fstab/grok_exporter/blob/master/CONFIG.md).

**Comment by HugoLafleur** [comment]
Hi,
Can you consider re-opening this? I have a use case where I need to calculate the median/p90/p99 latency over 5 minutes out of parsing an API's access logs. This could be achieved by exposing a configuration parameter that could then be passed to the `SummaryOpts` as object `MaxAge` when instanciating a `Summary` metric.

I understand @roidelapluie 's point, which relates to a quantile over dimensions (like `hosts`), but what I'm attempting to achieve is quantiles over time, which the client lib allows for, e.g. 

> _over the past 5 minutes there were 2500 API calls to route_ `/api/v1/route`_, the median response time was 10ms and the 90th percentile response time was 250ms_

**Comment by fstab** [comment]
Sounds like a legitimate use case, I'll re-open it. However all the time I spend on new `grok_exporter` features is currently focused on supporting multiple logfiles, so I will only get back to this when multiple logfiles are supported.

**Comment by HugoLafleur** [comment]
That's fair, thanks for reopening!
