### ISSUE TITLE
Count doesn't decreases even if there are no errors currently

### ISSUE THREAD

**Issue by Priyotosh008** [fstab/grok_exporter#27]
Hello All,

We have configured Grok exporter to monitor errors from the web service logs. We see that even when there are NO errors it still prints the past count of errors.

We have used "gauge" as the metric type and polling the log file every 5 secs.

Please see the config.yml below:
***************************
global:
    config_version: 2
input:
    type: file
    path: /ZAMBAS/logs/Healthcheck/AI/ai_17_grafana.log
    readall: true
    poll_interval_seconds: 5

grok:
    patterns_dir: ./patterns

metrics:
    - type: counter
      name: OutOfThreads
      help: Counter metric example with labels.
      match: '%{GREEDYDATA} WARN!! OUT OF THREADS: %{GREEDYDATA}'

    - type: counter
      name: OutOfMemory
      help: Counter metric example with labels.
      match: '%{GREEDYDATA}: Java heap space'

    - type: gauge
      name: NoMoreEndpointPrefix
      help: Counter metric example with labels.
      match: '%{GREEDYDATA}: APPL%{NUMBER:val1}: IO Exception: Connection refused %{GREEDYDATA}'
      value: '{{.val1}}'
      cumulative: false

    - type: gauge
      name: IOExceptionConnectionReset
      help: Counter metric example with labels.
      match: '   <faultstring>APPL%{NUMBER:val3}: IO Exception: Connection reset'
      value: '{{.val3}}'
      cumulative: false

    - type: gauge
      name: IOExceptionReadTimedOut
      help: Counter metric example with labels.
      match: '   <faultstring>APPL%{NUMBER:val4}: IO Exception: Read timed out'
      value: '{{.val4}}'
      cumulative: false

    - type: gauge
      name: FailedToConnectTo
      help: Counter metric example with labels.
      match: "   <faultstring>RUNTIME0013: Failed to connect to '%{URI:val5}"
      value: '{{.val5}}'
      cumulative: false

server:
    port: 9244
***************************

Result:
***************************
grok_exporter_lines_matching_total{metric="FailedToConnectTo"} 0
grok_exporter_lines_matching_total{metric="IOExceptionConnectionReset"} 0
grok_exporter_lines_matching_total{metric="IOExceptionReadTimedOut"} 3
grok_exporter_lines_matching_total{metric="NoMoreEndpointPrefix"} 0
grok_exporter_lines_matching_total{metric="OutOfMemory"} 0
grok_exporter_lines_matching_total{metric="OutOfThreads"} 0
***************************

Say, for 1 hr there were No errors, still it shows '3' errors and when an error does occurs it keeps adding up. So in total it becomes 4 and so on..it keeps on adding :(  

I want grok to show only the present data without adding previous values.

Please help us here on what am I doing wrong.

Thanks
Priyotosh

**Comment by fstab** [comment]
Looking at the current value of a counter is not very useful, that's true. However, Prometheus does not only store the current value, it also stores the time series of all previously observed values. Prometheus provides a powerful query language to evaluate time series data. Using the query language, you can learn how much the counter has increased within the last hour. This would correspond to the number of IOExceptionReadTimedOut exceptions in the last hour in your case.

**Comment by Priyotosh008** [comment]
Hello,

Thank you for the response.

I understand that Prometheus stores the time series of all previously observed values. But what I want is i don't want my current value to get added with the previous values.

Ex: (This is what I want)
Time                     No Of Errors
10:00 AM -                   5
10:30 AM -                 10
11:00 AM -                   2
11:30 AM -                   4

What is happening now is(the values are getting added):  
Time                     No Of Errors
10:00 AM -                   5
10:30 AM -                 15 (10 + 5)
11:00 AM -                 17 (15 + 2)
11:30 AM -                 21 (17 + 4)

Can you please help me how can I achieve this.


Thanks
Priyotosh

**Comment by fstab** [comment]
What exactly do you mean by _current value_? Is it the number of matching log lines within the last 30 minutes? Or is it some number that you get from the last log line?

**Comment by Priyotosh008** [comment]
By _current value_ I mean no of matching log lines lines. Nevertheless, I used rate() and increase() function to get only the last 30 mins data.
ex:
 round(increase(grok_exporter_lines_matching_total{instance="muclhi614:9144",job="grok",metric="OutOfThreads"}[30m]))
