### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by jstsch** [fstab/grok_exporter#29]
Would be great if we could run this on a Raspberry Pi or on Scaleway: https://www.scaleway.com/armv8-cloud-servers/

**Comment by fstab** [comment]
`grok_exporter` for Linux is built using a Docker image: [github.com/fstab/docker-grok_exporter-compiler](github.com/fstab/docker-grok_exporter-compiler)

In theory, it should be easy to built an ARM64 version by just basing the image on [arm64v8/ubuntu](https://hub.docker.com/r/arm64v8/ubuntu/).

However, I tried it and ran into [this issue](https://github.com/docker/for-mac/issues/1621) on Docker for Mac. I need to investigate how to solve this. Hard to tell whether this is hard or trivial.

**Comment by fstab** [comment]
I included a `linux-arm64v8` version in the [0.2.4 release](https://github.com/fstab/grok_exporter/releases). I hope this is the right version for you needs. I actually avoided the cross-platform Docker issue above, and built the release directly on a Scaleway server. That worked pretty well.

**Comment by jstsch** [comment]
Hi Fabian, that's great, thank you so much!
