### ISSUE TITLE
IIS Support

### ISSUE THREAD

**Issue by VR6Pete** [fstab/grok_exporter#30]
Hi there. 

Sorry if this is the wrong place to ask but has anyone built support for IIS logs? Cheers

Pete

**Comment by fstab** [comment]
Hi, I don't know if there is a `grok_exporter` config for IIS somewhere. However, grok patterns are used heavily with Logstash. If you google "grok" "iis" (without `grok_exporter`), you will find a lot of grok patterns for logstash that you can use as a starting point for configuring `grok_exporter` matches.
