### ISSUE TITLE
Grok Exporter does not support web.telemetry-path

### ISSUE THREAD

**Issue by varundmishra** [fstab/grok_exporter#34]
Grok Exporter does not support the web.telemetry-path option to set Path under which to expose metrics.
This is available in node_exporter as well as consul exporter, can this option be provided? 

eg. Line 74 here: https://github.com/prometheus/node_exporter/blob/master/node_exporter.go

**Comment by fstab** [comment]
This should be easy to implement, and you are not the first person to ask :)
Will include it in the next release.

**Comment by varundmishra** [comment]
Thanks Fabian, looking forward to the next release.

**Comment by fstab** [comment]
Made the path configurable in the config file:
```yaml
server:
    host: localhost
    port: 9144
    path: /bla
```
The code will be included in the next release.

**Comment by fstab** [comment]
Released v0.2.5 including the change.

**Comment by varundmishra** [comment]
@fstab 👍 Thanks will check this next week
