### ISSUE TITLE
This exporter does not do tailing over the file?

### ISSUE THREAD

**Issue by autumnw** [fstab/grok_exporter#35]
Hi,
My case is: I have the nginx access log file. I want the exporter can do tailing over the file. If the new lines in the file matches the pattern, then count it. And I want the have the expiration time(i.e. 5 mimutes) for the current counter.
Looks like this exporter can not do neither ?

Bests,
Autumn Wang

**Comment by fstab** [comment]
Looks like `grok_exporter` could be the right tool for you: It can follow a file like `tail -f` (see [File Input Type](https://github.com/fstab/grok_exporter/blob/master/CONFIG.md#file-input-type)) and it can expire old metrics when no corresponding log lines are found (see [retention](https://github.com/fstab/grok_exporter/blob/master/CONFIG.md#retention)).

**Comment by fstab** [comment]
Closing this issue. If you have any questions, feel free to re-open or create a new one.
