### ISSUE TITLE
Input filenames with timestamp

### ISSUE THREAD

**Issue by woogers** [fstab/grok_exporter#44]
Hello,
I've seen that support for multiple files is one of the most requested features, but would it be possible to use a file that has a datestamp in the filename? I'm monitoring an application that appends the current date and time to its log files. I know that wildcards that are being considered as part of multiple file support would 'solve' this issue, but it would potentially mean reading through dozens of log files when all I'm really interested in is the most recent one.

Thanks.

Example filename structure:
![image](https://user-images.githubusercontent.com/974415/46013538-9f01ec00-c09a-11e8-959b-6ab808692cdb.png)

**Comment by fstab** [comment]
This is a very good question. There are a couple of things related to multiple log files where I don't have a good answer yet:

* In your case, how do you read only the latest file if you configure `server-*.log` as the filename pattern?
* Also in your case: If log lines are only written to the latest file, how would `grok_exporter` know that it can stop tailing the older files?
* Apart from your example, there might be other scenarios where logrotate renames all log files. Renaming is sometimes similar to creating a new file and deleting the old file. How would `grok_exporter` avoid reading files a second time when the new copies are created?

Of course `grok_exporter` can solve this if we introduce very specific configuration options, like _"this part of the filename is a timestamp and I only want to get log lines from the latest time stamp"_ or _"this part of the filename is a logrotate number and I am only interested in the lowest number"_. However, if the configuration is too specific there will be a lot of cases that are not covered.

If you have any idea how a good configuration for this might look like, please share them. I really am not sure what the best approach is.

**Comment by jwood-krg** [comment]
The Nagios plugin check_logfiles works around this by supporting two config items: a logfile location and a rotation pattern. There is also the predefined pattern [MOD_LOG_ROTATE](https://github.com/lausser/check_logfiles/blob/master/plugins-scripts/Nagios/CheckLogfiles.pm#L3874) for Apache access logs. This pattern finds the newest log matching the pattern `access\.log\.\d{10}`.

It doesn't exactly apply here, but as check_logfiles is written in Perl, you can also script the config file for non-standard log patterns, such as using `$(date +%Y%m%d).log` as your logfile pattern. Maybe the `path:` config item of grok_exporter could support regex, and use `mtime` to choose the newest file matching the pattern?

**Comment by fstab** [comment]
Wildcards in file names are now supported with release 1.0.0.RC1. Configuration is in [CONFIG.md](https://github.com/fstab/grok_exporter/blob/master/CONFIG.md).
