### ISSUE TITLE
Regex Capture Groups

### ISSUE THREAD

**Issue by Krajiyah** [fstab/grok_exporter#45]
Release: v0.2.5

I have the following log line I am trying to grok pattern match:

`{"blah": "foo", "somethin": "baz", "status": 200}`

My Grok Pattern (tested on https://regex101.com, and has captured value of `200`):

`STATUS "status":\s+([^",}]*)`

My Grok Metric (Config v2):

```
match: '%{STATUS:status}'
labels:
    status: '{{.status}}'
```

I want .status to be just `200`, but instead I am getting `"status": 200`

The grok patter in `match` seems to be using the whole match sequence in the pattern defintion rather than the capture group. Is this a bug or a feature?

**Comment by fstab** [comment]
You should not confuse capture groups and named patterns. If you write `%{STATUS:status}` you are saying that everything that is matched by the pattern `STATUS` will be stored in the variable `status`. This has nothing to do with the capture group used in the `STATUS` pattern.

To achieve what you want, you could try something like this:

```yaml
match: '"status":\s+%{NUMBER:status_number}'
labels:
    status: '{{.status_number}}'
```
The variable `status_number` contains the match of the `NUMBER` pattern. The `NUMBER` pattern is defined in file `patterns/grok-patterns` which is included in `grok_exporter`.

**Comment by Krajiyah** [comment]
Thanks!
