### ISSUE TITLE
Exporter enters high CPU state and stops processing log lines

### ISSUE THREAD

**Issue by kfreem02** [fstab/grok_exporter#58]
Issue observed with 0.26, 0.27 and source build from master on April 25.

I have configured 3 instances of grok_exporter on CentOS.  2 instances run without issue, but 1 will only export metrics for a few minutes before entering a high CPU state.  In high CPU state the exporter still responds to scrape requests.  The backlog is growing at 3-4 rows per second.  While operating normally, the "bad" instance grok_exporter_lines_processing_time_microseconds_total is < 500 µs, and this metric drops to 0 once the instance enters high cpu state.

What debug information can I collect to help investigate this issue?

**Comment by kfreem02** [comment]
Config for the instance that enters high CPU state
global:
    config_version: 2
input:
    type: file
    path: /data/all_f5_asm_block.log
    readall: false # Read from the beginning of the file? False means we start at the end of the file and read only new lines.
grok:
    patterns_dir: /etc/grok/patterns
    additional_patterns:
metrics:
    - type: counter
      name: bigp_asm_block
      help: Count of ASM blocks by clientIP and URI
      match: '%{SYSLOGTIMESTAMP:LoggedEventTime} %{HOSTNAME:instance} ASM:unit_hostname="%{HOSTNAME}",management_ip_address="%{IP:HostIP1}",management_ip_address_2="",http_class_name="%{PATH}",web_application_name="%{PATH:WebAppName}",policy_name="%{PATH}",policy_apply_date="%{TIMESTAMP_ISO8601}",violations="%{DATA:Violations}",support_id="%{INT}",request_status="%{DATA:Status}",response_code="%{INT}",ip_client="%{IP:ClientIP}",route_domain="%{DATA}",method="%{WORD}",protocol="%{WORD}",query_string="%{DATA}",x_forwarded_for_header_value="%{DATA}",sig_ids="%{DATA}",sig_names="%{DATA}",date_time="%{TIMESTAMP_ISO8601}",severity="%{LOGLEVEL:Severity}",attack_type="%{DATA:AttackType}",geo_location="%{DATA:GeoLocation}",ip_address_intelligence="%{DATA:IP_Intelligence}",username="%{DATA}",sub_violations="%{DATA:SubViolations}",%{DATA},uri="%{URIPATH:Uri}",%{GREEDYDATA}'
      labels:
          client_ip: '{{.ClientIP}}'
          web_app_name: '{{.WebAppName}}'
          status: '{{.Status}}'
          severity: '{{.Severity}}'
          attack_type: '{{.AttackType}}'
          violations: '{{.Violations}}'
          uri: '{{.Uri}}'
          geo_location: '{{.GeoLocation}}'
          ip_intelligence: '{{.IP_Intelligence}}'
server:
    host: 0.0.0.0
    port: 9146

**Comment by kfreem02** [comment]
Screenshot of metrics for misbehaving service:
![Screen Shot 2019-04-29 at 2 04 30 PM](https://user-images.githubusercontent.com/36552670/56920102-f67c9600-6a87-11e9-9526-67bd8cc7df7a.png)

**Comment by fstab** [comment]
This sounds like a hard-to-find bug. There are two parts in grok_exporter: The first part handles file system events and reads log lines from log files, the second part does the pattern matching.

As a first step we need to find out which of those is the culprit. Could you configure `poll_interval_seconds` in your input section? This disables file system event processing and just reads the log files every n seconds. It has drawbacks and should not be necessary, but it could give us a hint. If this makes the problem go away, the error is likely in the file system event processing. If the problem is still there with this configuration, the problem is likely in pattern matching.

**Comment by raokrutarth** [comment]
I'm seeing the same issue so I tried:
![image](https://user-images.githubusercontent.com/8570223/57412707-7d2b2480-71a6-11e9-8bc2-177ce47601cb.png)

But the metric that generally fluctuates around 100-500 new entries per second, the total seems to be getting stalled.

![image](https://user-images.githubusercontent.com/8570223/57412749-aba8ff80-71a6-11e9-83a6-abf63f6eea9d.png)

**Comment by fstab** [comment]
I'd love to reproduce it. Could you post the match and an example line? Maybe if I write a small test that runs the line through the match 500 times/second I can reproduce it.

**Comment by raokrutarth** [comment]
The logs are pretty large so I've included a subset (can't attach a file. Can upload elsewhere too):
Logs: https://justpaste.it/7i7qo

Patterns with lower than expected matches:

`%{TIMESTAMP_ISO8601}\s+%{WORD}\s+xyz-tsdbd\[%{NUMBER}\]:\s+%{DATA}[Rr]eceived\s+new%{DATA}notif%{GREEDYDATA}`

`%{TIMESTAMP_ISO8601}\s+%{WORD}\s+xyz-tsdbd\[%{NUMBER}\]:\s+%{DATA}(([pP]rocessed%{DATA}notification)|(notification%{DATA}[Pp]rocessed))%{GREEDYDATA}`

`%{TIMESTAMP_ISO8601}\s+%{WORD}\s+xyz-tsdbd\[%{NUMBER}\]:\s+%{DATA}((dropp%{DATA}notification)|(notification%{DATA}dropp))%{GREEDYDATA}`

**Comment by fstab** [comment]
I still cannot reproduce it. I created a `config.yaml` file with the matches above as `match1`, `match2`, and `match3`, and `stdin` as input type. Then I copied the log lines into `logfile.log`, and ran the following to generate traffic:
```
(while true ; do cat logfile.log ; sleep 0.001 ; done) | grok_exporter -config ./config.yaml
```
With the Prometheus query `rate(match1[5m])` I can see the number of matches per second. This is around 1.2k for match1, 5.1k for match2, and 2.4k for match3. These values are almost constant, even though the throughput is much higher than the 500 entries / second in your experiment. I don't experience any significant changes or lost matches. Memory consumption of grok_exporter is constant.

Do you have any idea how I could reproduce the error?

**Comment by raokrutarth** [comment]
I'm using file as input instead of stdin. Would you recommend using stdin?

**Comment by fstab** [comment]
No, I would not recommend it. It's just an easy way to run a quick test.

It would be interesting to know if the error persists with `stdin`. If switching to `stdin` solves the problem, then there must be a bug in the `file` input with `poll_interval_seconds`. Could you check that?

**Comment by raokrutarth** [comment]
Set the input to stdin:
![image](https://user-images.githubusercontent.com/8570223/58056998-23b4e500-7b18-11e9-88d2-efe1ed3f70da.png)

Used the command `tail -f /var/log/messages | ./grok_exporter -config ./nae-grok-autogen.yaml >& /dev/null &` to run the process and verified the exporter is running on remote device.

After seeing multiple the relevant log messages that should have matched, verified http://grokconstructor.appspot.com/do/match#result detects match on eatch one.

But the counter below still showed 0 count:
```
- help: count of incoming notifications in tsdbd
  match: '%{TIMESTAMP_ISO8601}\s+%{WORD}\s+xyz-tsdbd\[%{NUMBER}\]:\s+%{DATA}[Rr]eceived\s+new%{DATA}notif%{GREEDYDATA}'
  name: benchmark_tsdbd_incoming_notif_log
  type: counter
```

![image](https://user-images.githubusercontent.com/8570223/58056985-14ce3280-7b18-11e9-9a2d-98a3a27e8c2d.png)

**Comment by raokrutarth** [comment]
I have a fairly high number of counters and use `summary` metric types frequently as well. Could that have an impact on the matches?

**Comment by fstab** [comment]
If you see the error with `tail -f /var/log/messages | ./grok_exporter...` maybe you can find some example log messages, put them into an `logfile.log` file and reproduce the same error with `(while true ; do cat logfile.log ; sleep 0.001 ; done) | grok_exporter...`.

Then you could attach the `logfile.log` file and your `config.yaml` here so I can reproduce the error on my machine.

**Comment by raokrutarth** [comment]
[logfile.log](https://github.com/fstab/grok_exporter/files/3237841/logfile.log)

[config.txt](https://github.com/fstab/grok_exporter/files/3237843/config.txt)

Unable to upload the config with the `.yaml` extension. Using `.yaml` during execution.

**Comment by raokrutarth** [comment]
The log file is very small subset of the actual log

**Comment by fstab** [comment]
Thanks for the example files. `grok_exporter` uses the [Oniguruma regular expression library](https://github.com/kkos/oniguruma/) for pattern matching. The `grok_exporter` release is statically linked to Oniguruma version 5.9.6. In your example, the `benchmark_tsdbd_incoming_notif_log` metric is `0` with the current `grok_exporter` release, but if I update Oniguruma to the current version 6.9.2 it works.

I will create a new release with an updated Oniguruma version, then you patterns should work. However, it will take two weeks.

In the meantime, you could either build `grok_exporter` from source using the latest Oniguruma library, or you refactor your patterns so that they work with Oniguruma 5.9.6. However, I cannot tell you exactly what's the breaking change between the two Oniguruma versions.

**Comment by raokrutarth** [comment]
What are the commands to build the exporter with the latest library version on Ubuntu?

**Comment by fstab** [comment]
The `release.sh` script is used to build the official releases. The official releases use oniguruma version 5.9.6. If you want to build your own version from source code, you need to install `go` and `gcc`, and build `grok_exporter` with `go install .`. This is also described here: https://github.com/fstab/grok_exporter#how-to-build-from-source

**Comment by raokrutarth** [comment]
The official golang `golang:1.12.5` and `golang:1.11.10` docker images already have `go` and `gcc` installed. From the errors I shared earlier, it appears the issue in related to the static linking even though Oniguruma release 6.9.2 installed correctly. Please see my steps above.

**Comment by fstab** [comment]
If you want to build with `grok_exporter` with your own Oniguruma version please run `go install .` and not `./release.sh`.

You could have a look at the commands in `.travis.yml` for reference. This runs with every commit and builds `grok_exporter` with different combinations, Oniguruma 5.9.6 and 6.7.0, static and dynamic linking. Resuls are here: https://travis-ci.org/fstab/grok_exporter/

I currently have limited Internet so I cannot check what's in the `golang` Docker image. But I can make a release with an updated Oniguruma version next week.

**Comment by raokrutarth** [comment]
Makes sense. It'll be easier for me to wait since I don't have permissions to the `/usr/...` directories on my machine. Appreciate it!

**Comment by fstab** [comment]
Sorry that it took so long, but I finally found the time to make rel 0.2.8. It uses Oniguruma 6.9.2.

**Comment by kfreem02** [comment]
I have installed 0.28 and am no longer seeing the issue.  Thank you for the fix!
