### ISSUE TITLE
Feature request: Retention does not work for metrics without labels.

### ISSUE THREAD

**Issue by sumitshatwara** [fstab/grok_exporter#60]
It will be great if we can use retention for metrics values without labels.

Currently, retention is only supported with labels in metrics.

Our issue: While conversion of units of values in file, i.e. from KiB/s to MiB/s, I am observing two different values in metrics, which eventually display two different plots / lines in graph dashboard of Grafana.

example,
`metrics:`    
`     - type: gauge`
`     name: bandwidth_randwrite`
`     help: FIO Bandwidth Random Write Gauge Metrics`
`     match: '  write: IOPS=%{GREEDYDATA}, BW=%{NUMBER:val2}%{GREEDYDATA:kibs} %{GREEDYDATA}'`
`     value: '{{if eq .kibs "KiB/s"}}{{divide .val2 1024}}{{else}}{{.val2}}{{end}}'`
`     labels:`
`          bw_unit: '{{.kibs}}'`
`     cumulative: false`
`     retention: 1m`

Result Metrics:
`bandwidth_randwrite{bw_unit="KiB/s"} 2.209`
`bandwidth_randwrite{bw_unit="MiB/s"} 3.205`

**Comment by fstab** [comment]
I am not sure I understand the issue correctly. How does retention relate to converting values from KiB/s to MiB/s?

**Comment by sumitshatwara** [comment]
I was looking for approach. Anyways, my issue got resolved. Hence, closing it
