### ISSUE TITLE
duplicated metrics with node_exporter

### ISSUE THREAD

**Issue by kingbyteking** [fstab/grok_exporter#66]
I see grok-exporter output some go_mem* metrics by default. But all these metrics are already available with node-exporter. 
One important point is that some metrics display different help string between grok_exporter and node-exporter. This will get Prometheus to complain the difference.
e.g:
node-exporter: # HELP go_memstats_sys_bytes Number of bytes obtained from system.
grok-exporter: # HELP go_memstats_sys_bytes Number of bytes obtained by system. Sum of all system allocations.
Would you please remove duplicated metrics with node exporter or update the help text string?

**Comment by fstab** [comment]
A little bit of background for those who find this in their Google searches: The metric `go_memstats_sys_bytes` is produced by the Prometheus client library for the [Go programming language](https://github.com/prometheus/client_golang/blob/master/prometheus/go_collector.go#L106). That means, every exporter written in Go provides this metric. The metric shows the memory consumption of the exporter. This is useful to observe the behavior of the exporter itself, but it does not say anything about the system being monitored.

It's not a duplicate metric. It's just that both the `node_exporter` and `grok_exporter` are written in Go, so the both export this metric for observing the exporters' memory consumption.

The reason why there are different HELP messages is that `grok_exporter` uses an older version of the client library, and the message changed with the newer version used in `node_exporter`. I updated the client library, so with the next `grok_exporter` release the HELP messages should be the same. You can safely ignore the Prometheus warning.
