### ISSUE TITLE
should be runnable on localhost

### ISSUE THREAD

**Issue by joker234** [fstab/grok_exporter#7]
I use the [authguard](https://github.com/cherti/authguard) to set up SSL and Authentication to prevent the misuse of sensible data from our apache logs. Please implement an option for running the exporter on localhost like many other exporters do.

**Comment by fstab** [comment]
Hi, sorry for responding late, your request is totally reasonable and also easy to implement, I will do it in the next few days as soon as I have some time...

**Comment by fstab** [comment]
I added a `host` option in server config to restrict server to localhost. It's in rel. 0.1.4. Thanks for your request!
