### ISSUE TITLE
grok-exporter can't expose logs on network

### ISSUE THREAD

**Issue by AKIA-Kali** [fstab/grok_exporter#72]
@fstab, i have some troubles with grok-exporter, i don't understand what the problem is :

grok exporter work with this server config(i can see logs on http://localhost:9144/metrics):

![Capture](https://user-images.githubusercontent.com/55446493/69619829-8d202e00-103c-11ea-88b7-1d2a20642daa.PNG)

but not with this server configuration(nothing appear on http://localhost:9144/metrics):

![Capture](https://user-images.githubusercontent.com/55446493/69619796-7679d700-103c-11ea-977f-1baeb5823bc9.PNG)

Thank you in advance !

**Comment by fstab** [comment]
If you specify `host: localhost` the metrics are only exposed on the local machine (you can access the metrics on the same machine where grok_exporter is running) but not over the network. If you want access over the network, remove the `host: localhost` setting (or replace it with `host: 0.0.0.0`).

**Comment by AKIA-Kali** [comment]
ok thank you a lot for your answer and your time.
By the way, do you plan to add a feature who can allow us to give data to grok-exporter by a network flux

ps: your tool is incredible ! its an exceptional work !

**Comment by fstab** [comment]
I currently do not have any plan to add a new network input, but it should be easily possible to use the `stdin` input and direct network traffic to the standard input. For example with the `nc` tool you can listen on port `12345` and redirect it to grok_exporter's standard input like this:
```
nc -l -p 12345 | grok_exporter -config conrig.yaml
```

**Comment by AKIA-Kali** [comment]
ok thanks a lot !
