### ISSUE TITLE
Use * to read log files from multiple directories

### ISSUE THREAD

**Issue by rajat23495** [fstab/grok_exporter#73]
Hi, 
I want to read log files from multiple directories like we do it in filebeat using * but it does not seem to work in grok exporter like - 
/var/log/abc/*/*/logs/service.log

**Comment by fstab** [comment]
This is a feature that's long overdue, I am still planning to implement it but it's not ready yet. As of now you must start one grok_exporter instance per log file.

**Comment by rajat23495** [comment]
@fstab thanks for the update, actually i am running grok exporter as a daemonset in k8s cluster to ingest logs from different hosts in the cluster and since the pod names will be varying i cant hardcode these values.. anyways when can i expect this feature to be rolled out?

**Comment by fstab** [comment]
Unfortunately I cannot give you an ETA on this, but it's the top feature request on my list.

**Comment by fstab** [comment]
It's released now with version 1.0.0.RC1. Documentation is in [CONFIG.md](https://github.com/fstab/grok_exporter/blob/master/CONFIG.md). Please open a GitHub issue if there are any problems or questions about the implementation.
