### ISSUE TITLE
show count per file name 

### ISSUE THREAD

**Issue by OAkaren** [fstab/grok_exporter#75]
we have to monitor different applications. There are several log files for an application, all of which are identical in the beginning of the name. Is it possible to monitor these files with example * .log and then output the matches found per file name?

**Comment by fstab** [comment]
This is the most popular feature request, and I will implement it. However, I cannot give you an estimation of when it will be available. For now, you have to start one `grok_expoerter` instance per log file.

**Comment by fstab** [comment]
It's implemented now with release 1.0.0.RC1.
