### ISSUE TITLE
flag -disable-exporter-metrics not defined

### ISSUE THREAD

**Issue by KinderLi** [fstab/grok_exporter#86]
./grok_exporter -disable-exporter-metrics true -config ./etc/grok_config.yml
flag provided but not defined: -disable-exporter-metrics
Usage of ./grok_exporter:
  .....

**Comment by fstab** [comment]
Which version of `grok_exporter` are you using? The flag `-disable-exporter-metrics` was added to the source code a few days ago, but it's not in a release yet. You need to build `grok_exporter` from the `master` branch to make it work.

Apart from that, you should use either `-disable-exporter-metrics=true` or simply `-disable-exporter-metrics`, but you cannot use `-disable-exporter-metrics true`.

**Comment by KinderLi** [comment]
It looks like I need to build it from th e master branch. That's all right.
