### ISSUE TITLE
Set timestamps on retrospective matches

### ISSUE THREAD

**Issue by tomcorby** [fstab/grok_exporter#87]
If the server is ever restarted, I can either parse all existing matches with `readall: true` or wait for new data to come in. If I use `readall: true` then all matches show up at the time they were parsed, when the server restarted. 

The logs I'm parsing have timestamps, e.g:

`[12-03-2020 08:50:22] [info]  [client 127.0.0.1]`

Is there any way to parse this timestamp as the date to use in prometheus? 

Not sure if this relates to #71 as that sounds like an incomplete feature

**Comment by fstab** [comment]
Hi, sorry for the late reply, I'm trying to adapt my schedule to all the new Corona constraints...

Prometheus and Logfiles have very different concepts of timestamps:
* In logfiles, a timestamp says when an event like `client 127.0.0.1 connected` happened.
* In Prometheus, a timestamp says when the metrics were scraped from the exporter.

There might be multiple logfile events between two scrapes of Prometheus. Therefore Prometheus does not represent individual logfile events, but just counters or other aggregation metrics. For example, Prometheus tells you that at timestamp _x_ it counted _n_ `client 127.0.0.1 connected` events in total, but it cannot tell you when the individual logfile events happened.

Maybe I'm getting the question wrong, but I don't see how you could use logfile timestamps in Prometheus.

**Comment by tomcorby** [comment]
No worries, I was hoping there would be a way to tell prometheus they were retroactively collected but it sounds like that isn't the case.

I'll close this issue for now
